import { PropType, type PropTable } from "../types/Props";

export const CharInfoProps = {
  beardColor: { type: PropType.Number, default: 0, min: 0, max: 99 },
  beardType: { type: PropType.Number, default: 0, min: 0, max: 5 },
  build: { type: PropType.Number, default: 64, min: 0, max: 127 },
  createId: {
    type: PropType.Array,
    default: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    min: 0,
    max: 255,
    size: 16,
  },
  eyeAspect: { type: PropType.Number, default: 3, min: 0, max: 6 },
  eyeColor: { type: PropType.Number, default: 8, min: 0, max: 99 },
  eyeRotate: { type: PropType.Number, default: 4, min: 0, max: 7 },
  eyeScale: { type: PropType.Number, default: 4, min: 0, max: 7 },
  eyeType: { type: PropType.Number, default: 2, min: 0, max: 59 },
  eyeX: { type: PropType.Number, default: 2, min: 0, max: 12 },
  eyeY: { type: PropType.Number, default: 12, min: 0, max: 18 },
  eyebrowAspect: { type: PropType.Number, default: 3, min: 0, max: 6 },
  eyebrowColor: { type: PropType.Number, default: 1, min: 0, max: 99 },
  eyebrowRotate: { type: PropType.Number, default: 6, min: 0, max: 11 },
  eyebrowScale: { type: PropType.Number, default: 4, min: 0, max: 8 },
  eyebrowType: { type: PropType.Number, default: 6, min: 0, max: 24 },
  eyebrowX: { type: PropType.Number, default: 2, min: 0, max: 12 },
  eyebrowY: { type: PropType.Number, default: 10, min: 3, max: 18 },
  facelineColor: { type: PropType.Number, default: 0, min: 0, max: 9 },
  facelineMake: { type: PropType.Number, default: 0, min: 0, max: 11 },
  facelineType: { type: PropType.Number, default: 0, min: 0, max: 11 },
  facelineWrinkle: { type: PropType.Number, default: 0, min: 0, max: 11 },
  favoriteColor: { type: PropType.Number, default: 0, min: 0, max: 11 },
  fontRegion: { type: PropType.Number, default: 0, min: 0, max: 3 },
  gender: { type: PropType.Number, default: 0, min: 0, max: 1 },
  glassColor: { type: PropType.Number, default: 8, min: 0, max: 99 },
  glassScale: { type: PropType.Number, default: 4, min: 0, max: 7 },
  glassType: { type: PropType.Number, default: 0, min: 0, max: 19 },
  glassY: { type: PropType.Number, default: 10, min: 0, max: 20 },
  hairColor: { type: PropType.Number, default: 1, min: 0, max: 99 },
  hairFlip: { type: PropType.Number, default: 0, min: 0, max: 1 },
  hairType: { type: PropType.Number, default: 33, min: 0, max: 131 },
  height: { type: PropType.Number, default: 64, min: 0, max: 127 },
  moleScale: { type: PropType.Number, default: 4, min: 0, max: 8 },
  moleType: { type: PropType.Number, default: 0, min: 0, max: 1 },
  moleX: { type: PropType.Number, default: 2, min: 0, max: 16 },
  moleY: { type: PropType.Number, default: 20, min: 0, max: 30 },
  mouthAspect: { type: PropType.Number, default: 3, min: 0, max: 6 },
  mouthColor: { type: PropType.Number, default: 19, min: 0, max: 99 },
  mouthScale: { type: PropType.Number, default: 4, min: 0, max: 8 },
  mouthType: { type: PropType.Number, default: 23, min: 0, max: 35 },
  mouthY: { type: PropType.Number, default: 13, min: 0, max: 18 },
  mustacheScale: { type: PropType.Number, default: 4, min: 0, max: 8 },
  mustacheType: { type: PropType.Number, default: 0, min: 0, max: 5 },
  mustacheY: { type: PropType.Number, default: 10, min: 0, max: 16 },
  nickname: { type: PropType.String, default: "Mii", min: 1, max: 10 },
  noseScale: { type: PropType.Number, default: 4, min: 0, max: 8 },
  noseType: { type: PropType.Number, default: 1, min: 0, max: 17 },
  noseY: { type: PropType.Number, default: 9, min: 0, max: 18 },
  regionMove: { type: PropType.Number, default: 0, min: 0, max: 3 },
  reserved: { type: PropType.Number, default: 0, min: 0, max: 1 },
  type: { type: PropType.Number, default: 0, min: 0, max: 1 },
} as PropTable;
